#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/plan_inspector/config ]] && [[ -d /opt/ros/noetic/share/plan_inspector/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/plan_inspector/config
    cp -r /opt/ros/noetic/share/plan_inspector/config /home/$USER/.config/movel/config/plan_inspector/config
  fi
fi
