reachable_plan_stop_distance: 1.0

aux_clean_map:
  footprint: [[0.15, 0.15], [-0.15, 0.15], [-0.15, -0.15], [0.15, -0.15]]
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  always_send_full_costmap: false
  
  plugins: 
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: "/map"
    subscribe_to_updates: false

  inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 4.0

aux_sync_map:
  footprint: [[0.15, 0.15], [-0.15, 0.15], [-0.5, -0.15], [0.15, -0.15]]
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  always_send_full_costmap: false
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: "/move_base/global_costmap/costmap"
    subscribe_to_updates: true

  inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 4.0