angle_gains_init: [0.4, 0.0, 0.0]
angle_gains_final: [0.4, 0.01, 0.05]
dist_gains: [0.125, 0.0, 0.0] #0.25
dock_backwards: true
angle_tolerance: 0.0436332 
dist_tolerance: 0.01
dist_feasible: 2.0
max_linear_speed: 0.1
max_angular_speed: 0.1
min_angular_speed: 0.003
odom_topic: "odom"
