# Lidar pointcloud topic
points_topic: "/lidar_point_cloud/filtered"

# approximate sensor tilt angle [deg]
tilt_deg: 0.0

# approximate sensor height [m]
sensor_height: 0.0

# points with heights in [sensor_height - height_clip_range, sensor_height + height_clip_range] 
# will be used for floor detection
height_clip_range: 0.2

# minimum number of support points of RANSAC to accept a detected floor plane
floor_pts_thresh: 40

# verticality check thresold for the detected floor plane [deg]
floor_normal_thresh: 10.0

# if true, points with "non-"vertical normals will be filtered before RANSAC
use_normal_filtering: true

# "non-"verticality check threshold [deg]
normal_filter_thresh: 20.0
