# lidar pointcloud topic
points_topic: "/lidar_point_cloud/filtered"

# frame settings 
map_frame_id: "map" 
# odom_frame_id: "odom" 
odom_frame_id: "odom_icp" 
odom_subs_topic: "/hdl/odom"

# optimization params (general graph optimization (g2o))
# typical solvers: gn_var, gn_fix6_3, gn_var_cholmod, lm_var, lm_fix6_3, lm_var_cholmod, ... 
g2o_solver_type: "lm_var_cholmod" 
g2o_solver_num_iterations: 512      # max iteration for optimization

# constraint switches 
enable_gps: false
enable_imu_acceleration: false
enable_imu_orientation: false

# keyframe registration params for building 3d map
max_keyframes_per_update: 10      # take n latest received keyframes
keyframe_delta_trans: 1.0         # minimum translational distance between keyframes 
keyframe_delta_angle: 2.0         # minimum angular distance between keyframes (radian) 

# fix first node for optimization stability 
fix_first_node: true
fix_first_node_stddev: "10 10 10 1 1 1"
fix_first_node_adaptive: true

# loop closure params 
distance_thresh: 1.0            # radius of a node to become a loop candidate
accum_distance_thresh: 3.0      # if traveled distance between keyframes is > area, to be considered as a loop candidate
min_edge_interval: 1.0          # minimum distance from last loop closing
fitness_score_thresh: 0.5       # threshold

# scan matching params (this params can be the same like in scan_matching nodelet)
registration_method: "FAST_GICP"            # ICP, GICP, NDT, GICP_OMP, NDT_OMP, FAST_GICP(recommended), or FAST_VGICP
reg_num_threads: 4                          # number of threads (paralel processing)
reg_transformation_epsilon: 0.0001             # The maximum difference between two consecutive transformations in order to consider convergence
reg_maximum_iterations: 64                  # number of max Iteration for convergence searching.
reg_max_correspondence_distance: 2.0        # the maximum distance threshold between a point and its nearest neighbor correspondent in order to be considered in the alignment process
reg_max_optimizer_iterations: 20            # maximum number of iterations at the optimization step
reg_use_reciprocal_correspondences: false   # The correspondence type used for correspondence estimation.
reg_correspondence_randomness: 20           # Number of points used for covariance estimation
reg_resolution: 0.1                         # NDT resolution
reg_nn_search_method: "DIRECT7"             # NN search method

# Edge params 
# GPS 
gps_edge_robust_kernel: "NONE" 
gps_edge_robust_kernel_size: 1.0
gps_edge_stddev_xy: 20.0
gps_edge_stddev_z: 5.0
# IMU orientation 
imu_orientation_edge_robust_kernel: "NONE" 
imu_orientation_edge_stddev: 1.0
# IMU acceleration (gravity vector) 
imu_acceleration_edge_robust_kernel: "NONE" 
imu_acceleration_edge_stddev: 1.0
# ground plane 
floor_edge_robust_kernel: "NONE" 
floor_edge_stddev: 10.0

# scan matching (Robust Kernel)
# robust kernels: NONE, Cauchy, DCS, Fair, GemanMcClure, Huber, PseudoHuber, Saturated, Tukey, Welsch 
odometry_edge_robust_kernel: "NONE" 
odometry_edge_robust_kernel_size: 1.0
loop_closure_edge_robust_kernel: "Huber" 
loop_closure_edge_robust_kernel_size: 1.0
use_const_inf_matrix: false
const_stddev_x: 0.5
const_stddev_q: 0.1
var_gain_a: 20.0
min_stddev_x: 0.1
max_stddev_x: 5.0
min_stddev_q: 0.05
max_stddev_q: 0.2
# update params 
graph_update_interval: 1.5
map_cloud_update_interval: 3.0
map_cloud_resolution: 0.01