# Lidar pointcloud topic
points_topic: "/lidar_point_cloud/filtered"

# where the prefiltering process will take place
base_link_frame: "base_link"

# if true, clip the lidar pointcloud between distance_near_thresh and distance_far_thresh
use_distance_filter: true
distance_near_thresh: 0.5
distance_far_thresh: 100.0

# downsampling method. (NONE, VOXELGRID, or APPROX_VOXELGRID). For better result, use VOXELGRID
downsample_method: "VOXELGRID"

# resolution of the downsampled-pointcloud
downsample_resolution: 0.05        # 0.1 for outdoor, 0.05 for indoor

# (NONE, RADIUS, or STATISTICAL)
outlier_removal_method: "RADIUS"

# statistical outlier removal params
statistical_mean_k: 30        # number of neighbors
statistical_stddev: 1.2       # standard deviation

# radius outlier removal params
radius_radius: 0.5            # radius of circle
radius_min_neighbors: 2       # minimum number of points inside a circle