#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/orbomator/config ]] && [[ -d /opt/ros/noetic/share/orbomator/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/orbomator/config
    cp -r /opt/ros/noetic/share/orbomator/config /home/$USER/.config/movel/config/orbomator/config
  fi
fi
