stages:
  - build
  - deploy

# Merge Requests are icky to handle. If deployment of container is done as
# after a MR (i.e, inside devel), there runs a risk the a disconnected pipeline
# with a broken CI script. A false assumption that an updated container is
# deployed. However, deployment as part of a MR check could also mean that
# though the MR check has passed, it is possible that a merge not occur, and
# the container gets deployed unintentionally.

build_devel:
  stage: build
  image: registry.gitlab.com/movelai/seirios_ros/base:latest
  script:
    - colcon build
    - robot docker generate -r . -s . --target devel
  rules:
    #- if: '$CI_COMMIT_BRANCH == "devel"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="devel"'
  artifacts:
    paths:
      - Dockerfile


deploy_devel:
  stage: deploy
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  dependencies:
    - build_devel
  rules:
    #- if: '$CI_COMMIT_BRANCH == "devel"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="devel"'
  before_script:
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin
  script:
    - echo "$CI_COMMIT_SHA" > seirios_version
    - docker build --build-arg NAME=base --build-arg TAG=latest -t devel:$CI_COMMIT_SHA .
    - docker image tag devel:$CI_COMMIT_SHA $SEIRIOS_REGISTRYdevel:$CI_COMMIT_SHA
    - docker push $SEIRIOS_REGISTRYdevel:$CI_COMMIT_SHA
    - docker image tag devel:$CI_COMMIT_SHA $SEIRIOS_REGISTRYdevel:latest
    - docker push $SEIRIOS_REGISTRYdevel:latest
