stages:
  - build
  - build_again
  - deploy


# Merge Requests are icky to handle. If deployment of container is done as
# after a MR (i.e, inside devel), there runs a risk the a disconnected pipeline
# with a broken CI script. A false assumption that an updated container is
# deployed. However, deployment as part of a MR check could also mean that
# though the MR check has passed, it is possible that a merge not occur, and
# the container gets deployed unintentionally.

build_devel:
  stage: build
  image: registry.gitlab.com/movelai/seirios_ros/$SEIRIOS_DEV_BASE:latest
  script:
    - find . -name '*.h' -o -name '*.cpp' -o -name "*.cc" -o -name "*.hpp" | xargs clang-format -i
    - colcon build
    - robot docker generate -r . -s . --target devel
    - export MOVEL_LICENSE=true
    - colcon build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="devel"'
  artifacts:
    paths:
      - devel_Dockerfile


build_devel_again:
  stage: build_again
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  dependencies:
    - build_devel
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="devel"'
  script:
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin && docker build --build-arg NAME=registry.gitlab.com/movelai/seirios_ros/$SEIRIOS_DEV_BASE --build-arg TAG=latest -t $SEIRIOS_DEVEL:$CI_COMMIT_SHA -f devel_Dockerfile .

deploy_devel:
  stage: deploy
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  dependencies:
    - build_devel_again
  rules:
    - if: '$CI_COMMIT_BRANCH == "devel"'
  script:
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin
    - docker image tag $SEIRIOS_DEVEL:$CI_COMMIT_SHA $SEIRIOS_REGISTRY$SEIRIOS_DEVEL:$CI_COMMIT_SHA
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_DEVEL:$CI_COMMIT_SHA
    - docker image tag $SEIRIOS_DEVEL:$CI_COMMIT_SHA $SEIRIOS_REGISTRY$SEIRIOS_DEVEL:latest
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_DEVEL:latest

build_staging:
  stage: build
  image: registry.gitlab.com/movelai/seirios_ros/$SEIRIOS_DEV_BASE:latest
  script:
    #check for tagging
    #- colcon build
    #check for testing
    - mkdir debs/
    - mkdir -p /tmp/movel/debs/
    - robot package generate -r .
    - cp -r  /tmp/movel/debs/* debs/
    - robot docker generate -r . -s debs/ --target staging
    - robot package upload -r . --target staging -j $CI_JOB_TOKEN
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="staging"'
  artifacts:
    paths:
      - staging_Dockerfile
      - debs/

build_staging_2:
  stage: build_again
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  dependencies:
    - build_staging
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="staging"'
  script:
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin && docker build -t $SEIRIOS_STAGING:$CI_COMMIT_SHA -f staging_Dockerfile .

deploy_staging:
  stage: deploy
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  dependencies:
    - build_staging_again
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
  script:
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin
    - docker image tag $SEIRIOS_STAGING:$CI_COMMIT_SHA $SEIRIOS_REGISTRY$SEIRIOS_STAGING:$CI_COMMIT_SHA
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_STAGING:$CI_COMMIT_SHA
    - docker image tag $SEIRIOS_STAGING:$CI_COMMIT_SHA $SEIRIOS_REGISTRY$SEIRIOS_STAGING:latest
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_STAGING:latest

build_master:
  stage: build
  image: registry.gitlab.com/movelai/seirios_ros/$SEIRIOS_DEV_BASE:latest
  #tags:
  #  - ros
  script:
    #check for tagging
    #- colcon build
    #check for testing
    - export MOVEL_LICENSE=true
    - mkdir debs/
    - mkdir -p /tmp/movel/debs/
    - robot package generate -r .
    - cp -r  /tmp/movel/debs/* debs/
    - robot docker generate -r . -s debs/ --target master
    - robot package upload -r . --target master -j $CI_JOB_TOKEN
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="master"'
  artifacts:
    paths:
      - master_Dockerfile
      - debs/
    dotenv:
      - seirios_v.env

build_master_again:
  stage: build_again
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  dependencies:
    - build_master
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="master"'
  script:
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin && docker build -t $SEIRIOS_MASTER:$CI_COMMIT_SHA -f master_Dockerfile .

deploy_master:
  stage: deploy
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  dependencies:
    - build_master
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin
    - docker image tag $SEIRIOS_MASTER:$SEIRIOS_VERSION $SEIRIOS_REGISTRY$SEIRIOS_MASTER:$SEIRIOS_VERSION
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_MASTER:$SEIRIOS_VERSION
    - docker image tag $SEIRIOS_MASTER:$SEIRIOS_VERSION $SEIRIOS_REGISTRY$SEIRIOS_MASTER:latest
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_MASTER:latest

deploy_release:
  stage: deploy
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
  script:
    - export SEIRIOS_VERSION=$(cat seirios_release.yml | grep -oh "[0-9.]*$")
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin && docker pull registry.gitlab.com/movelai/seirios_ros/$SEIRIOS_MASTER:latest
    - docker image tag $SEIRIOS_MASTER:latest $SEIRIOS_REGISTRY$SEIRIOS_RELEASE:$SEIRIOS_VERSION
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_RELEASE:$SEIRIOS_VERSION
    - docker image tag $SEIRIOS_MASTER:latest $SEIRIOS_REGISTRY$SEIRIOS_RELEASE:latest
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_RELEASE:latest
