stages:
  - build
  - deploy


# Merge Requests are icky to handle. If deployment of container is done as
# after a MR (i.e, inside devel), there runs a risk the a disconnected pipeline
# with a broken CI script. A false assumption that an updated container is
# deployed. However, deployment as part of a MR check could also mean that
# though the MR check has passed, it is possible that a merge not occur, and
# the container gets deployed unintentionally.

build_devel:
  stage: build
  image: registry.gitlab.com/movelai/seirios_ros/$SEIRIOS_BASE:latest
  script:
    #lint
    - find . -name '*.h' -o -name '*.cpp' -o -name "*.cc" -o -name "*.hpp" | xargs clang-format -i
    - colcon build
    - robot docker generate -r . -s . --target devel
  rules:
    #- if: '$CI_COMMIT_BRANCH == "devel"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="devel"'
  artifacts:
    paths:
      - Dockerfile


deploy_devel:
  stage: deploy
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  dependencies:
    - build_devel
  rules:
    #- if: '$CI_COMMIT_BRANCH == "devel"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="devel"'
      #before_script:
      #- echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin
  script:
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin && docker build --build-arg NAME=registry.gitlab.com/movelai/seirios_ros/$SEIRIOS_BASE --build-arg TAG=latest -t $SEIRIOS_DEVEL:$CI_COMMIT_SHA .
    - echo $SEIRIOS_REGISTRY$SEIRIOS_DEVEL:$CI_COMMIT_SHA
    - docker image tag $SEIRIOS_DEVEL:$CI_COMMIT_SHA $SEIRIOS_REGISTRY$SEIRIOS_DEVEL:$CI_COMMIT_SHA
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_DEVEL:$CI_COMMIT_SHA
    - docker image tag $SEIRIOS_DEVEL:$CI_COMMIT_SHA $SEIRIOS_REGISTRY$SEIRIOS_DEVEL:latest
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_DEVEL:latest

build_staging:
  stage: build
  image: registry.gitlab.com/movelai/seirios_ros/$SEIRIOS_BASE:latest
  #tags:
  #  - ros
  script:
    #check for tagging
    #- colcon build
    #check for testing
    - robot docker generate -r . -s . --target staging
    - mkdir -p /tmp/movel/debs
    - robot package generate -r .
    - robot package upload -j $CI_JOB_TOKEN --target staging -r .
    - robot docker generate -r . -s . --target staging
    - robot package upload -r . --target staging -j $CI_JOB_TOKEN
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="staging"'
  artifacts:
    paths:
      - Dockerfile

deploy_staging:
  stage: deploy
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command: ["--registry-mirror", "https://registry.gitlab.com"]
  dependencies:
    - build_staging
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="staging"'
  script:
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin && docker build --build-arg NAME=registry.gitlab.com/movelai/seirios_ros/$SEIRIOS_BASE --build-arg TAG=latest -t $SEIRIOS_STAGING:$CI_COMMIT_SHA .
    - echo $SEIRIOS_REGISTRY$SEIRIOS_STAGING:$CI_COMMIT_SHA
    - docker image tag $SEIRIOS_STAGING:$CI_COMMIT_SHA $SEIRIOS_REGISTRY$SEIRIOS_STAGING:$CI_COMMIT_SHA
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_STAGING:$CI_COMMIT_SHA
    - docker image tag $SEIRIOS_STAGING:$CI_COMMIT_SHA $SEIRIOS_REGISTRY$SEIRIOS_STAGING:latest
    - docker push $SEIRIOS_REGISTRY$SEIRIOS_STAGING:latest
