# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
  - pre_merge_build_check
  - pre_build_check
  - build_parent
  - release

pre_merge_build_check_x86:
  stage: pre_merge_build_check
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^release\/.*/'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  image: registry.gitlab.com/movelai/seirios_ros/${SEIRIOS_DEV_PLUS}_x86:latest
  timeout: 3h
  tags:
    - ros
  script:
    - export USER=movel
    - mkdir -p /home/${USER}/seirios_ws/src
    - pwd
    - ls -la
    - cp -r /builds/movelai/seirios_ros /home/${USER}/seirios_ws/src
    - cd /home/${USER}/seirios_ws
    - >
      source /opt/ros/noetic/setup.bash
      && apt update
      && rosdep update
      && rosdep install --from-paths src --ignore-src -r -y
    - catkin_make --only-pkg-with-deps movel_seirios_msgs
    - catkin_make -DCATKIN_WHITELIST_PACKAGES=""

pre_build_check:
  stage: pre_build_check
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH =~ /^release\/.*/'
      when: manual
      allow_failure: false
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH =~ /^(feat|fix|refactor|ci)\/.*/'
      when: manual
      allow_failure: false
  script:
    - echo "Building image for $CI_COMMIT_BRANCH branch."
    - apk add jq
    - apk add curl
    - online=$(curl --header 'PRIVATE-TOKEN':' '"$FULLAPI"'' "https://gitlab.com/api/v4/runners/6924593"|jq -r '.online')
    - paused=$(curl --header 'PRIVATE-TOKEN':' '"$FULLAPI"'' "https://gitlab.com/api/v4/runners/6924593"|jq -r '.paused')
    - cp ci_yml/x86_64.yml x86_64.yml
    - >
      if [[ $online == 'true' && $paused == 'false' ]]; then 
        cp ci_yml/arm64_yml/arm64_native.yml arm64.yml
      else
        cp ci_yml/arm64_yml/arm64_qemu.yml arm64.yml
      fi
  artifacts:
    paths:
      - x86_64.yml
      - arm64.yml

build_x86_parent:
  stage: build_parent
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH =~ /^release\/.*/'
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH =~ /^(feat|fix|refactor|ci)\/.*/'
  trigger:
    include:
      - artifact: x86_64.yml
        job: pre_build_check
    strategy: depend
  needs: [pre_build_check]

build_arm64_parent:
  stage: build_parent
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH =~ /^release\/.*/'
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH =~ /^(feat|fix|refactor|ci)\/.*/'
  trigger:
    include:
      - artifact: arm64.yml
        job: pre_build_check
    strategy: depend
  needs: [pre_build_check]

staging_release:
  stage: release
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH =~ /^release\/.*/'
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command:
        - "--registry-mirror"
        - https://registry.gitlab.com
  timeout: 2h
  script:
    - apk add --no-cache git
    - export SEIRIOS_VERSION=$(cat seirios_release.yml | grep -oh "[0-9.]*$")
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - git config --global user.name ${GITLAB_USER_NAME}
    - git remote add tag-origin https://oauth2:${READ_WRITE_REPO_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - git tag ${SEIRIOS_VERSION}.rc --force
    - git push tag-origin ${SEIRIOS_VERSION}.rc --force -o ci.skip

master_release:
  stage: release
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command:
        - "--registry-mirror"
        - https://registry.gitlab.com
  timeout: 2h
  script:
    - apk add --no-cache git
    - export SEIRIOS_VERSION=$(cat seirios_release.yml | grep -oh "[0-9.]*$")
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - git config --global user.name ${GITLAB_USER_NAME}
    - git remote add tag-origin https://oauth2:${READ_WRITE_REPO_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - git tag ${SEIRIOS_VERSION} --force
    - git push tag-origin ${SEIRIOS_VERSION} --force -o ci.skip

    # push movel_seirios_msgs to public repo
    - cd .. && mkdir movel_msgs && cd movel_msgs
    - git clone https://gitlab.com/movelai_public/movel_seirios_msgs.git
    - cd .. && cp -r seirios_ros/src/movel_seirios_msgs/. movel_msgs/movel_seirios_msgs/. && cd movel_msgs/movel_seirios_msgs/
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - git config --global user.name ${GITLAB_USER_NAME}
    - git remote set-url origin https://oauth2:${READ_WRITE_REPO_TOKEN}@gitlab.com/movelai_public/movel_seirios_msgs.git
    - git add .
    - git commit -m "Commit from seirios-ros-version -- ${SEIRIOS_VERSION}" || true
    - git push origin master
    - git remote set-url origin https://oauth2:unknown@gitlab.com/movelai_public/movel_seirios_msgs.git && git remote remove origin

# ### hotfix test image

# build_master_x86_test:
#   stage: build_parent
#   rules:
#     - if: $CI_COMMIT_BRANCH == "fix/best-effort"
#   image: registry.gitlab.com/movelai/seirios_ros/${SEIRIOS_DEV_PLUS}_x86:latest
#   timeout: 4h
#   tags:
#     - ros
#   script:
#     - ls -al
#     - apt-get -y  update
#     - rosdep update
#     - export CUSTOM_ROS_DEP_INSTALL=$(rosdep install --reinstall --simulate --from-path src --ignore-src | awk '{print $3 }' | grep 'ros-\|python')
#     - export size=${#CUSTOM_ROS_DEP_INSTALL} 
#     - >
#       if [ $size<10 ]; then
#         echo "Some thing wrong with ros dep command, Kindly check it"
#         exit 1
#       fi
#     - echo $CUSTOM_ROS_DEP_INSTALL > ros_dep_install.txt
#     - rosdep install --from-paths src --ignore-src -r -y
#     - export MOVEL_LICENSE=RWBBX
#     - mkdir debs/
#     - mkdir -p /tmp/movel/debs/
#     - rospack find rtabmap 
#     - robot package generate -r . -m colcon
#     - cp -r  /tmp/movel/debs/* debs/
#     - ls -al debs/
#     - robot docker generate -r . -s debs/ --target master_x86
#   artifacts:
#     paths:
#       - master_x86_Dockerfile
#       - debs/
#       - ros_dep_install.txt

# build_docker_master_x86:
#   stage: deploy_docker
#   rules:
#     - if: $CI_COMMIT_BRANCH == "fix/best-effort"
#   image: docker:19.03.12
#   services:
#     - name: docker:19.03.12-dind
#       command:
#         - "--registry-mirror"
#         - https://registry.gitlab.com
#   dependencies:
#     - build_master_x86_test
#   timeout: 4h
#   tags:
#     - ros-docker
#   script:
#     - export BRANCH_NAME=fix-best-effort # branch name without slashes
#     - export SEIRIOS_VERSION=$(cat seirios_release.yml | grep -oh "[0-9.]*$")
#     - export TAG_LATEST_COMMIT=${SEIRIOS_VERSION}-${SEIRIOS_MASTER}_x86
#     - export REGISTRY_INTERIM_BUILD=${SEIRIOS_REGISTRY}${BRANCH_NAME}
#     - export CUSTOM_ROS_DEP_INSTALL=$(cat ros_dep_install.txt)
#     - export image_count=$( docker image ls out_image_master_x86:${SEIRIOS_VERSION} | wc -l)
#     - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin
#     - >
#       if [[ $image_count == '1' ]]; then 
#         docker pull registry.gitlab.com/movelai/seirios_ros/dev_plus_x86:latest && docker build --tag out_image_master_x86:${SEIRIOS_VERSION} --build-arg CUSTOM_ROS_DEP_INSTALL="${CUSTOM_ROS_DEP_INSTALL}" -f master_x86_Dockerfile .
#       fi
#     - docker image tag out_image_master_x86:${SEIRIOS_VERSION} $REGISTRY_INTERIM_BUILD:$TAG_LATEST_COMMIT
#     - docker push $REGISTRY_INTERIM_BUILD:$TAG_LATEST_COMMIT
#     - docker rmi out_image_master_x86:${SEIRIOS_VERSION} $REGISTRY_INTERIM_BUILD:$TAG_LATEST_COMMIT || true