#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/cmd_vel_mux/config ]] && [[ -d /opt/ros/noetic/share/cmd_vel_mux/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/cmd_vel_mux/config
    cp -r /opt/ros/noetic/share/cmd_vel_mux/config /home/$USER/.config/movel/config/cmd_vel_mux/config
  fi
fi
