; Auto-generated. Do not edit!


(cl:in-package cob_actions-msg)


;//! \htmlinclude SetFloatGoal.msg.html

(cl:defclass <SetFloatGoal> (roslisp-msg-protocol:ros-message)
  ((data
    :reader data
    :initarg :data
    :type cl:float
    :initform 0.0))
)

(cl:defclass SetFloatGoal (<SetFloatGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetFloatGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetFloatGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_actions-msg:<SetFloatGoal> is deprecated: use cob_actions-msg:SetFloatGoal instead.")))

(cl:ensure-generic-function 'data-val :lambda-list '(m))
(cl:defmethod data-val ((m <SetFloatGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_actions-msg:data-val is deprecated.  Use cob_actions-msg:data instead.")
  (data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetFloatGoal>) ostream)
  "Serializes a message object of type '<SetFloatGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'data))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetFloatGoal>) istream)
  "Deserializes a message object of type '<SetFloatGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'data) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetFloatGoal>)))
  "Returns string type for a message object of type '<SetFloatGoal>"
  "cob_actions/SetFloatGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetFloatGoal)))
  "Returns string type for a message object of type 'SetFloatGoal"
  "cob_actions/SetFloatGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetFloatGoal>)))
  "Returns md5sum for a message object of type '<SetFloatGoal>"
  "73fcbf46b49191e672908e50842a83d4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetFloatGoal)))
  "Returns md5sum for a message object of type 'SetFloatGoal"
  "73fcbf46b49191e672908e50842a83d4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetFloatGoal>)))
  "Returns full string definition for message of type '<SetFloatGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%float32 data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetFloatGoal)))
  "Returns full string definition for message of type 'SetFloatGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%float32 data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetFloatGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetFloatGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SetFloatGoal
    (cl:cons ':data (data msg))
))
