#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/liof/config ]] && [[ -d /opt/ros/noetic/share/liof/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/liof/config
    cp -r /opt/ros/noetic/share/liof/config /home/$USER/.config/movel/config/liof/config
  fi
fi
