obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [0.6, 0.3], [0.6, -0.3], [-0.6, -0.3], [-0.6,0.3] ]
#robot_radius: 0.18
footprint_padding: 0.0
inflation_radius: 0.4

observation_sources: laser_scan_sensor obs_cloud mock_scan #point_cloud_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

obs_cloud:
    data_type: PointCloud2
    topic: obstacles_cloud
    marking: true
    clearing: false
    min_obstacle_height: 0.00
    max_obstacle_height: 1.00
    
mock_scan:
    data_type: LaserScan
    topic: obstacles_scan
    marking: false
    clearing: true
    min_obstacle_height: 0.00
    max_obstacle_height: 1.00
    inf_is_valid: true

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
