controller_frequency: 5.0 #5.0
controller_patience: 5.0 # 3.0
base_local_planner: "teb_local_planner/TebLocalPlannerROS"
#base_local_planner: "pebble_local_planner::PebbleLocalPlanner"

planner_frequency: 1.0
planner_patience: 5.0 #5.0

max_planning_retries: -1
recovery_behavior_enabled: true #enable recovery based behaviour
clearing_rotation_allowed: true
oscillation_timeout: 15.0
oscillation_distance: 0.25

GlobalPlanner: 
  neutral_cost: 66
  cost_factor: 0.55
  lethal_cost: 253
  allow_unknown: false
