controller_frequency: 5.0 #5.0
controller_patience: 5.0 # 3.0
base_global_planner: "global_planner/GlobalPlanner"
# base_global_planner: "smac_planner/SmacPlanner"
# base_global_planner: "SBPLLatticePlanner" # only works with 0.05m global and local costmap resolution
base_local_planner: "teb_local_planner/TebLocalPlannerROS"
# base_local_planner: "pebble_local_planner::PebbleLocalPlanner"
# base_local_planner: "reg_pure_pursuit_local_planner/RegPurePursuitPlanner"
planner_frequency: 1.0
planner_patience: 5.0 #5.0

max_planning_retries: -1
recovery_behavior_enabled: true #enable recovery based behaviour
clearing_rotation_allowed: true
oscillation_timeout: 15.0
oscillation_distance: 0.25

recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

conservative_reset:
  reset_distance: 1.0
  layer_names: ["obstacle_layer", "lowbstacle_layer"]

# For rotate_recovery
TrajectoryPlannerROS:
  acc_lim_theta: 0.2
  max_vel_theta: 0.2
  min_in_place_vel_theta: 0.1
  yaw_goal_tolerance: 0.087

aggressive_reset:
  reset_distance: 0.0
  layer_names: ["obstacle_layer", "lowbstacle_layer"]
