base_global_planner: "global_planner/GlobalPlanner"
planner_frequency: 3.0
max_planning_retries: 0
recovery_behavior_enabled: false
clearing_rotation_allowed: false
oscillation_timeout: 5.0
oscillation_distance: 0.5

