multi_point_map:
  footprint: [ [0.135, 0.135], [0.135, -0.135], [-0.135, -0.135], [-0.135,0.135] ] # waffle 3

  map_type: voxel

  # Added m_ prefix to not get overwritten by costmap_common_params, to keep topic as /scan
  m_obstacle_layer:
      origin_z: -0.1
      z_resolution: 1.8 # This must be higher than the z coordinate of the mounted lidar
      z_voxels: 1 
      obstacle_range: 10.0 
      raytrace_range: 15.0 
      observation_sources: m_laser_scan_sensor

      m_laser_scan_sensor: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, min_obstable_height: 0.00, max_obstacle_height: 3.00, inf_is_valid: true}
          
  inflation_layer:
      enabled: true
      cost_scaling_factor: 1.0 
      inflation_radius: 0.3 

  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05 
  always_send_full_costmap: true
  plugins:
    - {name: m_obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}