frequency: 30
base_link_frame: base_link
two_d_mode: true
odom0: wheel_odom
odom0_config: [true, true, true,
               true,  true,  true,
               true,  true,  true,
               true,  true,  true,
               true,  true,  true]             
odom0_relative: true
odom0_pose_rejection_threshold: 10000000
odom0_twist_rejection_threshold: 10000000

odom1: rf2o_odom
odom1_config: [true, true, true,
               false,  false,  true,
               false,  false,  false,
               false,  false,  false,
               false,  false,  false]  
odom1_differential: true
odom1_pose_rejection_threshold: 10000000
odom1_twist_rejection_threshold: 10000000

use_control: false

