local_costmap:
  global_frame: map
  robot_base_frame: base_link_flattened
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05 #xy resolution of the voxel
  always_send_full_costmap: true
  transform_tolerance: 0.8
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: lowbstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    #- {name: ultrasound_layer, type: "range_sensor_layer::RangeSensorLayer"}
