footprint: [ [0.405, 0.32], [0.405, -0.32], [-0.405, -0.32], [-0.405,0.32] ]

# robot_radius: 0.38 #0.38 
# footprint_padding: 0.05 
map_type: voxel

obstacle_layer:
    origin_z: -0.1
    z_resolution: 1.8 #1.5 This must be higher than the z coordinate of the mounted lidar
    z_voxels: 1
    obstacle_range: 10.0 #10.0
    raytrace_range: 15.0 #15.0
    observation_sources: laser_scan_sensor #point_cloud_sensor

    laser_scan_sensor: {sensor_frame: base_link_flattened, data_type: LaserScan, topic: /ramp_scan, marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 1.80}
    #point_cloud_sensor: {sensor_frame: base_link_flattened, data_type: PointCloud2, topic: /cloud_segmented, marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 1.80}

lowbstacle_layer:
    origin_z: -0.1
    z_resolution: 1.8
    z_voxels: 1
    obstacle_range: 3.5 #if beyond this threshold, then will not mark as obstacle
    raytrace_range: 5.0 #5.0 Lower this value to detect nearer obstacles with better accuracy
    observation_sources: obs_cloud mock_scan #butt_scan1 butt_scan2
    publish_voxel_map: true

    obs_cloud:
       data_type: PointCloud2
       topic: /cloud_segmented
       sensor_frame: base_link_flattened
       marking: true
       clearing: true
       min_obstacle_height: 0.0
       max_obstacle_height: 0.99
        
    mock_scan:
       data_type: LaserScan
       topic: /ramp_scan
       sensor_frame: base_link_flattened
       marking: false
       clearing: true
       min_obstacle_height: 0.0
       max_obstacle_height: 1.00
       inf_is_valid: true
        
inflation_layer:
    enabled: true
    cost_scaling_factor: 6.0 #added in by John
    inflation_radius: 0.51 #0.45 #Minimum value: 0.379
    
dynamic_obstacle_layer:
    enabled: false
    map_tolerance: 0.2
    footprint_radius: 0.2
    range: 1.0

# static_layer:
#     enabled: true
#     map_topic: "/movel_office"
#     use_maximum: false
    
# static_map: 
#     map_topic: "/movel_office"

# range_sensor_layer:
#   topics: ["/sonar_range_lf", "/sonar_range_lb", "/sonar_range_rb", "/sonar_range_rf",  "/sonar_range_fl", "/sonar_range_fr"] #"/sonar_range_bl", "/sonar_range_br",
#   no_readings_timeout: 0.0 #If zero, this parameter has no effect. Otherwise if the layer does not receive sensor data for this amount of time, the layer will warn the user and the layer will be marked as not current.
#   clear_threshold: .3 #Cells with a probability lower than the clear_threshold are marked as free space in the master costmap. 
#   mark_threshold: 0.85 #Cells with a probability higher than the mark_threshold are marked as lethal obstacles in the master costmap.
#   clear_on_max_reading: true #Whether to clear the sensor readings on max. range
