#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/human_detection/config ]] && [[ -d /opt/ros/noetic/share/human_detection/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/human_detection/config
    cp -r /opt/ros/noetic/share/human_detection/config /home/$USER/.config/movel/config/human_detection/config
  fi
fi
