# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
  - build
  - build_docker


build_devel:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="devel"
  image: registry.gitlab.com/movelai/seirios_ros/${SEIRIOS_DEV_BASE}_arm64:latest
  timeout: 2h
  tags:
    - docker-arm
  script:
    - export MOVEL_LICENSE=RWBBX
    - robot docker generate -r . -s . --target devel_arm64
    - robot docker generate -r . -s . --target devel_arm64
  artifacts:
    when: always
    paths:
      - devel_arm64_Dockerfile
      - devel_arm64_Dockerfile
  cache:
    paths:
      - build/
      - devel/
    policy: pull-push

build_docker_devel_arm64_native:
  stage: build_docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="devel"
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command:
        - "--registry-mirror"
        - https://registry.gitlab.com
  dependencies:
    - build_devel
  tags:
    - arm-ros
  timeout: 12h
  script:
    - export SEIRIOS_VERSION=$(cat seirios_release.yml | grep -oh "[0-9.]*$")
    - export TAG_COMMIT_SHA=${SEIRIOS_VERSION}-${SEIRIOS_DEVEL}_arm64-${CI_COMMIT_SHA}
    - export TAG_LATEST_COMMIT=${SEIRIOS_VERSION}-${SEIRIOS_DEVEL}_arm64-latest-commit
    - export REGISTRY_IMTERIM_BUILD=${SEIRIOS_REGISTRY}interim_build
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin 
      && docker build --build-arg NAME=registry.gitlab.com/movelai/seirios_ros/${SEIRIOS_DEV_BASE}_arm64
      --build-arg TAG=latest --tag out_image -f devel_arm64_Dockerfile .
    - docker image tag out_image $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA
    - docker push $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA
    - docker image tag out_image $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT
    - docker push $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT
    - docker rmi out_image $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT

build_staging_arm64_native:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="staging"
  image: registry.gitlab.com/movelai/seirios_ros/${SEIRIOS_DEV_BASE}_arm64:latest
  timeout: 6h
  tags:
    - docker-arm
  script:
    - ls -al
    - apt-get -y  update
    - export CUSTOM_ROS_DEP_INSTALL=$(rosdep install --reinstall --simulate --from-path src --ignore-src | awk '{print $3 }' | grep 'ros-\|python')
    - echo $CUSTOM_ROS_DEP_INSTALL > ros_dep_install.txt
    - rosdep install --from-paths src --ignore-src -r -y
    - mkdir debs/
    - mkdir -p /tmp/movel/debs/
    - robot package generate -r . -m colcon
    - cp -r  /tmp/movel/debs/* debs/
    - ls -al debs/
    - robot docker generate -r . -s debs/ --target staging_arm64
    - robot package upload -r . --target staging_arm64 -j $CI_JOB_TOKEN
  artifacts:
    paths:
      - staging_arm64_Dockerfile
      - debs/
      - ros_dep_install.txt

build_docker_staging_arm_64_native:
  stage: build_docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="staging"
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command:
        - "--registry-mirror"
        - https://registry.gitlab.com
  dependencies:
    - build_staging_arm64_native
  timeout: 6h
  tags:
    - docker-arm
  script:
    - export SEIRIOS_VERSION=$(cat seirios_release.yml | grep -oh "[0-9.]*$")
    - export TAG_COMMIT_SHA=${SEIRIOS_VERSION}-${SEIRIOS_STAGING}_arm64-${CI_COMMIT_SHA}
    - export TAG_LATEST_COMMIT=${SEIRIOS_VERSION}-${SEIRIOS_STAGING}_arm64-latest-commit
    - export REGISTRY_IMTERIM_BUILD=${SEIRIOS_REGISTRY}interim_build
    - export CUSTOM_ROS_DEP_INSTALL=$(cat ros_dep_install.txt)
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin 
      && docker build --tag out_image --build-arg CUSTOM_ROS_DEP_INSTALL="${CUSTOM_ROS_DEP_INSTALL}" -f staging_arm64_Dockerfile .
    - docker image tag out_image $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA
    - docker push $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA
    - docker image tag out_image $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT
    - docker push $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT
    - docker rmi out_image $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT



### master 

build_master_arm64_native:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="master"
  image: registry.gitlab.com/movelai/seirios_ros/${SEIRIOS_DEV_BASE}_arm64:latest
  timeout: 6h
  tags:
    - docker-arm
  script:
    - export MOVEL_LICENSE=RWBBX
    - mkdir debs/
    - mkdir -p /tmp/movel/debs/
    - sudo apt-get -y  update
    - export CUSTOM_ROS_DEP_INSTALL=$(rosdep install --reinstall --simulate --from-path src --ignore-src | awk '{print $3 }' | grep 'ros-\|python')
    - echo $CUSTOM_ROS_DEP_INSTALL > ros_dep_install.txt
    - rosdep install --from-paths src --ignore-src -r -y
    - robot package generate -r . -m colcon
    - cp -r  /tmp/movel/debs/* debs/
    - robot docker generate -r . -s debs/ --target master_arm64
    - robot package upload -r . --target master_arm64 -j $CI_JOB_TOKEN
  artifacts:
    paths:
      - master_arm64_Dockerfile
      - debs/
      - ros_dep_install.txt

build_docker_master_arm_64_native:
  stage: build_docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="master"
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command:
        - "--registry-mirror"
        - https://registry.gitlab.com
  dependencies:
    - build_master_arm64_native
  timeout: 6h
  tags:
    - docker-arm
  script:
    - export SEIRIOS_VERSION=$(cat seirios_release.yml | grep -oh "[0-9.]*$")
    - export TAG_COMMIT_SHA=${SEIRIOS_VERSION}-${SEIRIOS_MASTER}_arm64-${CI_COMMIT_SHA}
    - export TAG_LATEST_COMMIT=${SEIRIOS_VERSION}-${SEIRIOS_MASTER}_arm64-latest-commit
    - export REGISTRY_IMTERIM_BUILD=${SEIRIOS_REGISTRY}interim_build
    - export CUSTOM_ROS_DEP_INSTALL=$(cat ros_dep_install.txt)
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin 
      && docker build --tag out_image --build-arg CUSTOM_ROS_DEP_INSTALL="${CUSTOM_ROS_DEP_INSTALL}" -f master_arm64_Dockerfile .
    - docker image tag out_image $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA
    - docker push $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA
    - docker image tag out_image $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT
    - docker push $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT
    - docker rmi out_image $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT

## Misc

build_staging_arm64_test:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "feature/orbslam-handler"
  image: registry.gitlab.com/movelai/seirios_ros/${SEIRIOS_DEV_BASE}_arm64:latest
  timeout: 12h
  tags:
    - ros
  script:
    - ls -al
    - apt-get -y  update
    - export CUSTOM_ROS_DEP_INSTALL=$(rosdep install --reinstall --simulate --from-path src --ignore-src | awk '{print $3 }' | grep 'ros-\|python')
    - echo $CUSTOM_ROS_DEP_INSTALL > ros_dep_install.txt
    - rosdep install --from-paths src --ignore-src -r -y
    - mkdir debs/
    - mkdir -p /tmp/movel/debs/
    - robot package generate -r . -m colcon
    - cp -r  /tmp/movel/debs/* debs/
    - ls -al debs/
    - robot docker generate -r . -s debs/ --target staging_arm64
    - robot package upload -r . --target staging_arm64 -j $CI_JOB_TOKEN
  artifacts:
    paths:
      - staging_arm64_Dockerfile
      - debs/
      - ros_dep_install.txt

build_docker_staging_arm64_test:
  stage: build_docker
  rules:
    - if: $CI_COMMIT_BRANCH == "feature/orbslam-handler"
  image: docker:19.03.12
  services:
    - name: docker:19.03.12-dind
      command:
        - "--registry-mirror"
        - https://registry.gitlab.com
  dependencies:
    - build_staging_arm64_test
  timeout: 12h
  tags:
    - ros-docker
  script:
    - export SEIRIOS_VERSION=$(cat seirios_release.yml | grep -oh "[0-9.]*$")
    - export TAG_COMMIT_SHA=${SEIRIOS_VERSION}-${SEIRIOS_STAGING}_arm64-${CI_COMMIT_SHA}-test
    - export TAG_LATEST_COMMIT=${SEIRIOS_VERSION}-${SEIRIOS_STAGING}_arm64-latest-commit-test
    - export REGISTRY_IMTERIM_BUILD=${SEIRIOS_REGISTRY}interim_build
    - export CUSTOM_ROS_DEP_INSTALL=$(cat ros_dep_install.txt)
    - echo $DOCKERDTRW | docker login registry.gitlab.com/movelai --username Docker-DT-RW --password-stdin 
      && docker build --tag out_image --build-arg CUSTOM_ROS_DEP_INSTALL="${CUSTOM_ROS_DEP_INSTALL}" -f staging_arm64_Dockerfile .
    - docker image tag out_image $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA
    - docker push $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA
    - docker image tag out_image $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT
    - docker push $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT
    - docker rmi out_image $REGISTRY_IMTERIM_BUILD:$TAG_COMMIT_SHA $REGISTRY_IMTERIM_BUILD:$TAG_LATEST_COMMIT