#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/yaml_utils/config ]] && [[ -d /opt/ros/noetic/share/yaml_utils/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/yaml_utils/config
    cp -r /opt/ros/noetic/share/yaml_utils/config /home/$USER/.config/movel/config/yaml_utils/config
  fi
fi
