#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/anti_shin_buster/config ]] && [[ -d /opt/ros/noetic/share/anti_shin_buster/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/anti_shin_buster/config
    cp -r /opt/ros/noetic/share/anti_shin_buster/config /home/$USER/.config/movel/config/anti_shin_buster/config
  fi
fi
