frame_id:               "base_link"
subscribe_depth:        false
subscribe_rgb:          false
subscribe_scan_cloud:   true
approx_sync:            true

Rtabmap:
  DetectionRate:    "2"

RGBD:
  NeighborLinkRefining:   false
  AngularUpdate:          "1.2"
  LinearUpdate:           "1.0"
  #Proximity Detection
  ProximityBySpace:             true        # Enable Lidar loop closing
  ProximityMaxGraphDepth:       "0"           # if 0, old scan can be taken into account as loop closing candidate
  ProximityPathMaxNeighbors:    "1"        
  LocalRadius:                  "3.0"         # must be higher than ProximityPathFilteringRadius, 1.5x
  ProximityPathFilteringRadius: "2.0"         # Loop closure radius
  ProximityMaxPaths:            "2"
  ProximityOdomGuess:           true
  ProximityAngle:               "180"         # Max angle difference for loop closing.
  OptimizeMaxError:             "0.0"        # For rejecting loop closure, 0 means all loop closures will be registered

Kp:
  MaxFeatures:                  "-1"          # -1 means we are not using rgbd

Mem:
  NotLinkedNodesKept:           false
  STMSize:                      "30"
  LaserScanVoxelSize:           "0.2"

Reg:
  Strategy:                     "1"           # 0=Vis, 1=Icp, 2=VisIcp
  Force3DoF:                    true

Grid:
  CellSize:                     "0.1"
  RangeMax:                     "10"          # Max range for 2d map
  GroundIsObstacle:             false
  FromDepth:                    false
  RayTracing:                   true
  3D:                           true 
 
  PreVoxelFiltering:            true

  #PCL CropBox filtering 
  FootprintLength:              "0.81"        # Should be tuned according robot dimensions
  FootprintWidth:               "0.635"
  FootprintHeight:              "0.7"

  #Normal Segmentation 
  NormalsSegmentation:          false
  NormalK:                      "40"
  MaxGroundAngle:               "30"          # max slope
  MaxGroundHeight:              "0.2"

  #Clustering  
  ClusterRadius:                "0.2"        # Cluster tolerance
  MinClusterSize:               "30"

  #Flat obstacle 
  FlatObstacleDetected:          false
  MaxObstacleHeight:            "3.0"        # Max height of the lidar, pointcloud above this will be deleted.

  #After segmentation filtering 
  NoiseFilteringRadius:         "0.0"
  NoiseFilteringMinNeighbors:   "0"

GridGlobal:
  #Auxiliary function 
  Eroded:                       false
  FootprintRadius:              "0.0"      # Patch size for 2d map generation. (Make free space under each keyframe with size of this value)
  OccupancyThr:                 "0.5"

Icp:
  VoxelSize:                    "0.1"
  PointToPlaneK:                "20"
  PointToPlaneRadius:           "0"
  PointToPlane:                 true
  Iterations:                   "100"
  Epsilon:                      "0.001"
  MaxTranslation:               "4.0"
  MaxCorrespondenceDistance:    "1.5"
  PMOutlierRatio:               "0.7"
  CorrespondenceRatio:          "0.35"
  PointToPlaneGroundNormalsUp:  "0.8"
  RangeMin:                     "0.5"
  RangeMax:                     "20"        # Max Range for loop closure

Optimizer:
  Robust:                       true      # Using Vertigo
  Strategy:                     "1"         # 0=TORO, 1=g2o, 2=GTSAM and 3=Ceres
  Iterations:                   "100" 
  Epsilon:                      "0.01"
  GravitySigma:                 "0.3"

g2o:
  Solver:                       "2"         # 0=csparse 1=pcg 2=cholmod 3=Eigen
  Optimizer:                    "0"         # 0=Levenberg 1=GaussNewton


Vis:
  PnPRefineIterations:          "0"
