// Generated by gencpp from file cob_map_accessibility_analysis/CheckPerimeterAccessibilityResponse.msg
// DO NOT EDIT!


#ifndef COB_MAP_ACCESSIBILITY_ANALYSIS_MESSAGE_CHECKPERIMETERACCESSIBILITYRESPONSE_H
#define COB_MAP_ACCESSIBILITY_ANALYSIS_MESSAGE_CHECKPERIMETERACCESSIBILITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace cob_map_accessibility_analysis
{
template <class ContainerAllocator>
struct CheckPerimeterAccessibilityResponse_
{
  typedef CheckPerimeterAccessibilityResponse_<ContainerAllocator> Type;

  CheckPerimeterAccessibilityResponse_()
    : accessible_poses_on_perimeter()  {
    }
  CheckPerimeterAccessibilityResponse_(const ContainerAllocator& _alloc)
    : accessible_poses_on_perimeter(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _accessible_poses_on_perimeter_type;
  _accessible_poses_on_perimeter_type accessible_poses_on_perimeter;





  typedef boost::shared_ptr< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckPerimeterAccessibilityResponse_

typedef ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<std::allocator<void> > CheckPerimeterAccessibilityResponse;

typedef boost::shared_ptr< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse > CheckPerimeterAccessibilityResponsePtr;
typedef boost::shared_ptr< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse const> CheckPerimeterAccessibilityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator1> & lhs, const ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.accessible_poses_on_perimeter == rhs.accessible_poses_on_perimeter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator1> & lhs, const ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cob_map_accessibility_analysis

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f2833ac60e33edc572866f291ef3669";
  }

  static const char* value(const ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f2833ac60e33edcULL;
  static const uint64_t static_value2 = 0x572866f291ef3669ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_map_accessibility_analysis/CheckPerimeterAccessibilityResponse";
  }

  static const char* value(const ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D[] accessible_poses_on_perimeter 	  # array of accessible poses on the perimeter of the circle\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accessible_poses_on_perimeter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckPerimeterAccessibilityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_map_accessibility_analysis::CheckPerimeterAccessibilityResponse_<ContainerAllocator>& v)
  {
    s << indent << "accessible_poses_on_perimeter[]" << std::endl;
    for (size_t i = 0; i < v.accessible_poses_on_perimeter.size(); ++i)
    {
      s << indent << "  accessible_poses_on_perimeter[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.accessible_poses_on_perimeter[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_MAP_ACCESSIBILITY_ANALYSIS_MESSAGE_CHECKPERIMETERACCESSIBILITYRESPONSE_H
