// Generated by gencpp from file cob_map_accessibility_analysis/CheckPointAccessibility.msg
// DO NOT EDIT!


#ifndef COB_MAP_ACCESSIBILITY_ANALYSIS_MESSAGE_CHECKPOINTACCESSIBILITY_H
#define COB_MAP_ACCESSIBILITY_ANALYSIS_MESSAGE_CHECKPOINTACCESSIBILITY_H

#include <ros/service_traits.h>


#include <cob_map_accessibility_analysis/CheckPointAccessibilityRequest.h>
#include <cob_map_accessibility_analysis/CheckPointAccessibilityResponse.h>


namespace cob_map_accessibility_analysis
{

struct CheckPointAccessibility
{

typedef CheckPointAccessibilityRequest Request;
typedef CheckPointAccessibilityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckPointAccessibility
} // namespace cob_map_accessibility_analysis


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cob_map_accessibility_analysis::CheckPointAccessibility > {
  static const char* value()
  {
    return "c42c7449dffc73e50011cd7a1eb83e23";
  }

  static const char* value(const ::cob_map_accessibility_analysis::CheckPointAccessibility&) { return value(); }
};

template<>
struct DataType< ::cob_map_accessibility_analysis::CheckPointAccessibility > {
  static const char* value()
  {
    return "cob_map_accessibility_analysis/CheckPointAccessibility";
  }

  static const char* value(const ::cob_map_accessibility_analysis::CheckPointAccessibility&) { return value(); }
};


// service_traits::MD5Sum< ::cob_map_accessibility_analysis::CheckPointAccessibilityRequest> should match
// service_traits::MD5Sum< ::cob_map_accessibility_analysis::CheckPointAccessibility >
template<>
struct MD5Sum< ::cob_map_accessibility_analysis::CheckPointAccessibilityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cob_map_accessibility_analysis::CheckPointAccessibility >::value();
  }
  static const char* value(const ::cob_map_accessibility_analysis::CheckPointAccessibilityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_map_accessibility_analysis::CheckPointAccessibilityRequest> should match
// service_traits::DataType< ::cob_map_accessibility_analysis::CheckPointAccessibility >
template<>
struct DataType< ::cob_map_accessibility_analysis::CheckPointAccessibilityRequest>
{
  static const char* value()
  {
    return DataType< ::cob_map_accessibility_analysis::CheckPointAccessibility >::value();
  }
  static const char* value(const ::cob_map_accessibility_analysis::CheckPointAccessibilityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cob_map_accessibility_analysis::CheckPointAccessibilityResponse> should match
// service_traits::MD5Sum< ::cob_map_accessibility_analysis::CheckPointAccessibility >
template<>
struct MD5Sum< ::cob_map_accessibility_analysis::CheckPointAccessibilityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cob_map_accessibility_analysis::CheckPointAccessibility >::value();
  }
  static const char* value(const ::cob_map_accessibility_analysis::CheckPointAccessibilityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cob_map_accessibility_analysis::CheckPointAccessibilityResponse> should match
// service_traits::DataType< ::cob_map_accessibility_analysis::CheckPointAccessibility >
template<>
struct DataType< ::cob_map_accessibility_analysis::CheckPointAccessibilityResponse>
{
  static const char* value()
  {
    return DataType< ::cob_map_accessibility_analysis::CheckPointAccessibility >::value();
  }
  static const char* value(const ::cob_map_accessibility_analysis::CheckPointAccessibilityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COB_MAP_ACCESSIBILITY_ANALYSIS_MESSAGE_CHECKPOINTACCESSIBILITY_H
