#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/map_updater/config ]] && [[ -d /opt/ros/noetic/share/map_updater/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/map_updater/config
    cp -r /opt/ros/noetic/share/map_updater/config /home/$USER/.config/movel/config/map_updater/config
  fi
fi
