# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----

# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: movelai/kinetic-development:v0.9.4
# A workaround to set the internal ssh-agent away from root
  run-as-user: 0

pipelines:
  branches:
    feature/*:
      - step:
         # Not clear why this is required when by default Pipelines uses docker.
         # But things break without setting docker as services.
         services:
           - docker
         script:
          - cd ..
          - mkdir -p /home/${USER}/test_ws/src
          - cp -r build /home/${USER}/test_ws/src/$BITBUCKET_REPO_SLUG
          - cd /home/${USER}/test_ws
          - curl -O -L --user lwxryan:$CURL_DOWN https://api.bitbucket.org/2.0/repositories/movelai/movel_collection/downloads/movel-robot-$MOVEL_ROBOT_V.tar.gz
          - tar -xzvf movel-robot-$MOVEL_ROBOT_V.tar.gz
          - cli/install
          - /bin/bash
          - chown -R  ${USER}:${USER} /home/${USER}
          - source /opt/ros/kinetic/setup.bash
          - catkin init
          - rosdep update
          - robot workspace resolve-dependencies -u lwxryan -t $CURL_DOWN
          - catkin build -j2
          #- Add Tests
    hotfix/*:
      - step:
         # Not clear why this is required when by default Pipelines uses docker.
         # But things break without setting docker as services.
         services:
           - docker
         script:
          - cd ..
          - mkdir -p /home/${USER}/test_ws/src
          - cp -r build /home/${USER}/test_ws/src/$BITBUCKET_REPO_SLUG
          - cd /home/${USER}/test_ws
          - curl -O -L --user lwxryan:$CURL_DOWN https://api.bitbucket.org/2.0/repositories/movelai/movel_collection/downloads/movel-robot-$MOVEL_ROBOT_V.tar.gz
          - tar -xzvf movel-robot-$MOVEL_ROBOT_V.tar.gz
          - cli/install
          - /bin/bash
          - chown -R  ${USER}:${USER} /home/${USER}
          - source /opt/ros/kinetic/setup.bash 
          - catkin init
          - rosdep update
          - robot workspace resolve-dependencies -u lwxryan -t $CURL_DOWN
          - catkin build -j2
    devel:
      - step:
         # Not clear why this is required when by default Pipelines uses docker.
         # But things break without setting docker as services.
         services:
           - docker
         script:
          - cd ..
          - mkdir -p /home/${USER}/test_ws/src
          - cp -r build /home/${USER}/test_ws/src/$BITBUCKET_REPO_SLUG
          - cd /home/${USER}/test_ws
          - curl -O -L --user lwxryan:$CURL_DOWN https://api.bitbucket.org/2.0/repositories/movelai/movel_collection/downloads/movel-robot-$MOVEL_ROBOT_V.tar.gz
          - tar -xzvf movel-robot-$MOVEL_ROBOT_V.tar.gz
          - cli/install
          - /bin/bash
          - chown -R  ${USER}:${USER} /home/${USER}
          - source /opt/ros/kinetic/setup.bash
          - catkin init
          - rosdep update
          - robot workspace resolve-dependencies -u lwxryan -t $CURL_DOWN
          - catkin build -j2
          #- Add Test checks
          #- Add CMake checks
          # Temp Fix
          - robot release package --ros
          - robot release upload -u lwxryan -t $CURL_UP
    master:
      - step:
         # Not clear why this is required when by default Pipelines uses docker.
         # But things break without setting docker as services.
         services:
           - docker
         script:
          - cd ..
          - mkdir -p /home/${USER}/test_ws/src
          - cp -r build /home/${USER}/test_ws/src/$BITBUCKET_REPO_SLUG
          - cd /home/${USER}/test_ws
          - curl -O -L --user lwxryan:$CURL_DOWN https://api.bitbucket.org/2.0/repositories/movelai/movel_collection/downloads/movel-robot-$MOVEL_ROBOT_V.tar.gz
          - tar -xzvf movel-robot-$MOVEL_ROBOT_V.tar.gz
          - cli/install
          - /bin/bash
          - chown -R  ${USER}:${USER} /home/${USER}
          - source /opt/ros/kinetic/setup.bash
          - catkin init
          - rosdep update
          - robot workspace resolve-dependencies -u lwxryan -t $CURL_DOWN
          - catkin build -j2
          - robot release package --ros
          - robot release upload -u lwxryan -t $CURL_UP
