standalone_tags:
  [
    #{id: 0, size: 0.168}
  ]

tag_bundles:
  [
    {
      name: 'tag_0',
      layout:
        [
          {id: 0, size: 0.142, x: -0.45},
          {id: 1, size: 0.142, x: 0.54}
        ]
    },
    {
      name: 'tag_2',
      layout:
        [
          {id: 2, size: 0.142, x: -0.56},
          {id: 3, size: 0.142, x: 0.64}
        ]
    },
  ]
  
remove_duplicates: true
publish_tag_detections_image: true
