// Generated by gencpp from file cob_actions/SetBoolFeedback.msg
// DO NOT EDIT!


#ifndef COB_ACTIONS_MESSAGE_SETBOOLFEEDBACK_H
#define COB_ACTIONS_MESSAGE_SETBOOLFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_actions
{
template <class ContainerAllocator>
struct SetBoolFeedback_
{
  typedef SetBoolFeedback_<ContainerAllocator> Type;

  SetBoolFeedback_()
    : message()  {
    }
  SetBoolFeedback_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::cob_actions::SetBoolFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_actions::SetBoolFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SetBoolFeedback_

typedef ::cob_actions::SetBoolFeedback_<std::allocator<void> > SetBoolFeedback;

typedef boost::shared_ptr< ::cob_actions::SetBoolFeedback > SetBoolFeedbackPtr;
typedef boost::shared_ptr< ::cob_actions::SetBoolFeedback const> SetBoolFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_actions::SetBoolFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_actions::SetBoolFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cob_actions::SetBoolFeedback_<ContainerAllocator1> & lhs, const ::cob_actions::SetBoolFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cob_actions::SetBoolFeedback_<ContainerAllocator1> & lhs, const ::cob_actions::SetBoolFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cob_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cob_actions::SetBoolFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_actions::SetBoolFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_actions::SetBoolFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_actions::SetBoolFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_actions::SetBoolFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_actions::SetBoolFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_actions::SetBoolFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::cob_actions::SetBoolFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_actions::SetBoolFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_actions/SetBoolFeedback";
  }

  static const char* value(const ::cob_actions::SetBoolFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_actions::SetBoolFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::cob_actions::SetBoolFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_actions::SetBoolFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetBoolFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_actions::SetBoolFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_actions::SetBoolFeedback_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_ACTIONS_MESSAGE_SETBOOLFEEDBACK_H
