// Generated by gencpp from file cob_actions/SetIntGoal.msg
// DO NOT EDIT!


#ifndef COB_ACTIONS_MESSAGE_SETINTGOAL_H
#define COB_ACTIONS_MESSAGE_SETINTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_actions
{
template <class ContainerAllocator>
struct SetIntGoal_
{
  typedef SetIntGoal_<ContainerAllocator> Type;

  SetIntGoal_()
    : data(0)  {
    }
  SetIntGoal_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::cob_actions::SetIntGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_actions::SetIntGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SetIntGoal_

typedef ::cob_actions::SetIntGoal_<std::allocator<void> > SetIntGoal;

typedef boost::shared_ptr< ::cob_actions::SetIntGoal > SetIntGoalPtr;
typedef boost::shared_ptr< ::cob_actions::SetIntGoal const> SetIntGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_actions::SetIntGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_actions::SetIntGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cob_actions::SetIntGoal_<ContainerAllocator1> & lhs, const ::cob_actions::SetIntGoal_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cob_actions::SetIntGoal_<ContainerAllocator1> & lhs, const ::cob_actions::SetIntGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cob_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cob_actions::SetIntGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_actions::SetIntGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_actions::SetIntGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_actions::SetIntGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_actions::SetIntGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_actions::SetIntGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_actions::SetIntGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::cob_actions::SetIntGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda5909fbe378aeafULL;
  static const uint64_t static_value2 = 0x85e547e830cc1bb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_actions::SetIntGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_actions/SetIntGoal";
  }

  static const char* value(const ::cob_actions::SetIntGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_actions::SetIntGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"int32 data\n"
;
  }

  static const char* value(const ::cob_actions::SetIntGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_actions::SetIntGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIntGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_actions::SetIntGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_actions::SetIntGoal_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_ACTIONS_MESSAGE_SETINTGOAL_H
