#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/fbsm/config ]] && [[ -d /opt/ros/noetic/share/fbsm/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/fbsm/config
    cp -r /opt/ros/noetic/share/fbsm/config /home/$USER/.config/movel/config/fbsm/config
  fi
fi
