init: #inital profile at start, should contain all filters to be used during the lifetime of the node
  tf_message_filter_target_frame: base_link

  scan_filter_chain:

  - name: BoxFilter1
    type: laser_filters/LaserScanBoxFilter
    params:
      box_frame: base_link
      max_x: 1
      max_y: 1
      max_z: 1
      min_x: -1
      min_y: -1
      min_z: -1
      invert: False
      switch_: False # "switch_" is an additional parameter to switch the laser on/off

  - name: LaserScanPolygonFilter
    type: laser_filters/LaserScanPolygonFilter
    params:
      polygon_frame: base_link
      # polygon: [ [-1, 1], [1, 1], [1, -1], [-1, -1] ] #unit square
      polygon: [ [1,1], [1,2], [2,2], [2,1], [1,1], [-1,-1], [-1,-2], [-2,-2], [-2,-1], [-1,-1]]
      polygon_padding: 0
      invert: False
      switch_: True

  - name: LaserScanAngularBoundsFilter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -1.57
      upper_angle: 1.57
      switch_: False

  - name: ScanShadowsFilter
    type: laser_filters/ScanShadowsFilter
    params:
      min_angle: 10
      max_angle: 170
      neighbors: 10
      window: 2
      remove_shadow_start_point: True
      switch_: True

  - name: LaserScanFootprintFilter
    type: laser_filters/LaserScanFootprintFilter
    params:
      inscribed_radius: 0.5
      switch_: True

limit_fov: 

  tf_message_filter_target_frame: base_link

  scan_filter_chain:

  - name: BoxFilter1
    type: laser_filters/LaserScanBoxFilter
    params:
      box_frame: base_link
      max_x: 2
      max_y: 2
      max_z: 2
      min_x: -2
      min_y: -2
      min_z: -2
      invert: False
      switch_: False


  - name: LaserScanAngularBoundsFilter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -0.57
      upper_angle: 0.57
      switch_: True

  - name: ScanShadowsFilter
    type: laser_filters/ScanShadowsFilter
    params:
      min_angle: 10
      max_angle: 170
      neighbors: 10
      window: 2
      remove_shadow_start_point: True
      switch_: True

  - name: LaserScanPolygonFilter
    type: laser_filters/LaserScanPolygonFilter
    params:
      polygon_frame: base_link
      polygon: [ [-1, 1], [1, 1], [1, -1], [-1, -1] ] #unit square
      # polygon: [ [1,1], [1,2], [2,2], [2,1], [1,1], [-1,-1], [-1,-2], [-2,-2], [-2,-1], [-1,-1]]
      polygon_padding: 0
      invert: False
      switch_: True

got_box: 

  tf_message_filter_target_frame: base_link

  scan_filter_chain:

  - name: BoxFilter1
    type: laser_filters/LaserScanBoxFilter
    params:
      box_frame: base_link
      max_x: 1
      max_y: 1
      max_z: 1
      min_x: -1
      min_y: -1
      min_z: -1
      invert: False
      switch_: True 

  - name: LaserScanAngularBoundsFilter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -1.3
      upper_angle: 1.3
      switch_: False

  - name: ScanShadowsFilter
    type: laser_filters/ScanShadowsFilter
    params:
      min_angle: 10
      max_angle: 170
      neighbors: 10
      window: 2
      remove_shadow_start_point: True
      switch_: True

no_filter: 

  tf_message_filter_target_frame: base_link

  scan_filter_chain:
  - name: BoxFilter1
    type: laser_filters/LaserScanBoxFilter
    params:
      box_frame: base_link
      max_x: 0
      max_y: 0
      max_z: 0
      min_x: -0
      min_y: -0
      min_z: -0
      invert: False
      switch_: False 

  - name: LaserScanAngularBoundsFilter
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -0.785
      upper_angle: 0.785
      switch_: False 

  - name: ScanShadowsFilter
    type: laser_filters/ScanShadowsFilter
    params:
      min_angle: 10
      max_angle: 170
      neighbors: 20
      window: 2
      remove_shadow_start_point: True
      switch_: False 
