#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/vodom_vodom/config ]] && [[ -d /opt/ros/noetic/share/vodom_vodom/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/vodom_vodom/config
    cp -r /opt/ros/noetic/share/vodom_vodom/config /home/$USER/.config/movel/config/vodom_vodom/config
  fi
fi
