#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/broadcast_pose/config ]] && [[ -d /opt/ros/noetic/share/broadcast_pose/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/broadcast_pose/config
    cp -r /opt/ros/noetic/share/broadcast_pose/config /home/$USER/.config/movel/config/broadcast_pose/config
  fi
fi
