# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----

# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: movelai/kinetic-test-kernel:v0.1.0
# A workaround to set the internal ssh-agent away from root
  run-as-user: 0

pipelines:
  default:
     - step:
         # Not clear why this is required when by default Pipelines uses docker.
         # But things break without setting docker as services.
         services:
           - docker
         script:
           #- mkdir -p /home/$USER/.ssh
           #- touch /home/$USER/.ssh/known_hosts
           #- ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
           ## This is required because pipeline's ssh-agent looks into /root/ for the ssh-key, but we need to test the build in the actual environment.
           #- cp -r /home/$USER/.ssh/ /root/.ssh/
           #- su movel
           #- cd /home/$USER/
           #- git clone git@bitbucket.org:movelai/ros-ci.git .ci
           #- .ci/bitbucket.sh
          - cd ..
          - cp -r build /home/movel/catkin_ws/src/$BITBUCKET_REPO_SLUG
          - cd /home/movel/catkin_ws
          - curl -O -L --user lwxryan:$CURL_DOWN https://api.bitbucket.org/2.0/repositories/movelai/movel_collection/downloads/movel-robot-v0.1.0.tar.gz
          - tar -xzvf movel-robot-v0.1.0.tar.gz
          - cli/install
          - rm  movel-robot-v0.1.0.tar.gz
          - ls 
          - bash
          - rosdep update
          - robot setup dependencies -u lwxryan -t $CURL_DOWN --custom
          - catkin build
          - robot release create
          - robot release upload -u lwxryan -t $CURL_UP

