#!/bin/bash

set -e

if [[ =="deployment" ]] && [[ -d /home/$USER/.config/movel/config/ ]]; then
  if [[ ! -d /home/$USER/.config/movel/config/planner_adjuster/config ]] && [[ -d /opt/ros/noetic/share/planner_adjuster/config ]]; then
    mkdir -p /home/$USER/.config/movel/config/planner_adjuster/config
    cp -r /opt/ros/noetic/share/planner_adjuster/config /home/$USER/.config/movel/config/planner_adjuster/config
  fi
fi
