point_topic: "/cloud_pcd"
sensor_height: 1.18
num_seg: 1
num_lpr: 20
num_iter: 3

# how many m from cloud bottom
th_seeds_upper: 0.1 

# how many m down from cloud_bottom + th_seeds_upper
th_seeds_lower: 0.2 

th_dist: 0.3
sensor_model: 16
sor_mean_k: 50 
sor_sigma_mult: 0.25 