publish_pointcloud: true
publish_pose: true
localize_only: false
reset_map: false

load_map: false
pointcloud_frame_id: "orb_map"
target_frame_id: "orb_camera_link"
camera_frame_id: "orb_camera_link"
min_num_kf_in_map: 5

ORBextractor/nFeatures: 1000
ORBextractor/scaleFactor: 1.2
ORBextractor/nLevels: 8
ORBextractor/iniThFAST: 20
ORBextractor/minThFAST: 7

camera_fps: 30
camera_rgb_encoding: true
ThDepth: 40.0
depth_map_factor: 1000.0
load_calibration_from_cam: true 
camera_fx: 334.919
camera_fy: 334.919
camera_cx: 325.85
camera_cy: 180.49
camera_k1: 0.0
camera_k2: 0.0
camera_p1: 0.0
camera_p2: 0.0
camera_k3: 0.0
camera_baseline: 40.19